name: CheckAccess V2 Go SDK Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-**

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0
      - name: Set up Golang
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22.0"
          check-latest: true
      - name: Test
        run: |
            make lint test